### ISSUE TITLE
Can't import WebsocketIOClientWorker in Colab

### ISSUE THREAD

**Issue by vvmnnnkv** [OpenMined/PyGrid#274] opened 2019-08-20 07:26 UTC
This was working yesterday:
`from grid.workers.socketio_client import WebsocketIOClientWorker`

Now it gives following error:
```
OSError                                   Traceback (most recent call last)
<ipython-input-2-fe68181326e4> in <module>()
      3 import sys
      4 import torch
----> 5 from grid.workers.socketio_client import WebsocketIOClientWorker
      6 
      7 # Updated numpy serializer that returns array of bytes instead of string

20 frames
/usr/local/lib/python3.6/dist-packages/dns/rdtypes/IN/WKS.py in <module>()
     23 from dns._compat import xrange
     24 
---> 25 _proto_tcp = socket.getprotobyname('tcp')
     26 _proto_udp = socket.getprotobyname('udp')
     27 

OSError: protocol not found
```

**Comment by mari-linhares** [comment] 2019-08-20 13:34
@vvmnnnkv can you share the colab notebook?

**Comment by vvmnnnkv** [comment] 2019-08-20 21:58
@mari-linhares please see:
https://colab.research.google.com/drive/1Homa4YIcrOx3Rn5ZPkSLqS-5vCb9ovB-

**Comment by mari-linhares** [comment] 2019-09-02 00:30
Hey @vvmnnnkv,

Sorry for the delay, I'm investigating it, potentially is something specific to Colab. I think we may need to explicitly install the protocol.

**Comment by vvmnnnkv** [comment] 2019-09-19 17:03
Hi @mari-linhares 
It was working before this commit:
https://github.com/OpenMined/PyGrid/commit/9885bfac7c7a8d481db3d1ed5e8f1b628d0501b2
E.g. rev. 70093e146e6f36d6310abbebfe2c85b680283150 works fine.
It seems that the reason is addition of `eventlet` package that needs system file `/etc/protocols`, that file is missing on Colab.
Adding `!apt-get install netbase` on top of the notebook resolves the problem, here's an updated notebook if you interested: https://colab.research.google.com/drive/1oIF7re73cDHCubpWNebonvpyuJBkM4R0

This might help if you plan to make example notebooks Colab friendly :)

**Comment by mari-linhares** [comment] 2019-09-19 18:23
That's great, thanks for the "fix"!!! I'll close this issue for now since we know what the problem is and is not PyGrid explicitly related.

> This might help if you plan to make example notebooks Colab friendly :)

Yes, indeed! If you have anything in mind we would love hosting the examples here.

**Closed by mari-linhares** 2019-09-19 18:23 UTC

**Comment by its-AsifNawaz** [comment] 2021-09-12 06:03
Thanks this solve my issue too. .
