### ISSUE TITLE
Create Network API endpoints for Roles

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#640] opened 2020-07-17 10:52 UTC
We need a variety of API endpoints for roles so that we can easily permission the PyGrid application. Here are a few commonalities between all endpoints:

- All endpoints should be supported in both HTTP and Websockets. Please follow the same organizational structure and workflow that was used in the static FL project for this.
- Successful returns should send back the role object itself.
- Note that on these API routes, there is no `static` or `dynamic` prefix. This is because this table is shared between both workflows, and therefore the API endpoints should follow the same methodology.

### Create Role - `POST /roles`
**Request body:** `name`, `can_edit_settings`, `can_create_users`, `can_edit_roles`, `can_manage_nodes`
**Description:** Creates a new role. Only users with the permission of `can_edit_roles` can create a role. Duh.

### Get Role - `GET /roles/{id}`
**Request body:** N/A
**Description:** Gets an individual role. Only users with the permission of `can_edit_settings` can get a role.

### Get Roles - `GET /roles`
**Request body:** N/A
**Description:** Gets all roles. Only users with the permission of `can_edit_settings` can get all roles.

### Update Role - `PUT /roles/{id}`
**Request body:** `name`, `can_edit_settings`, `can_create_users`, `can_edit_roles`, `can_manage_nodes`
**Description:** Updates a role. Only users with the permission of `can_edit_roles` can edit a role.

### Delete Role - `DELETE /roles/{id}`
**Request body:** N/A
**Description:** Deletes a role. Only users with the permission of `can_edit_roles` can delete a role.

**Comment by Benardi** [comment] 2020-07-31 21:45
@cereallarceny Duplicate of #634 ?

**Comment by cereallarceny** [comment] 2020-08-03 10:18
No @Benardi, this one is for the Network. While #634 is for the Node. They have identical API's but have different role structures.

**Closed** 2020-09-25 10:01 UTC
Labels: Type: Epic :call_me_hand:
